### ISSUE TITLE
Upgrade node

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lib_jobs#662]
See pulibrary/dacs_handbook#157 for context - upgrade to Node 20.11.1 or higher or Node 18.19.1 or higher

**Comment by maxkadel** [comment]
On deploy ran into the following error:

```
App 388205 output: Error: The application encountered the following error: You have already activated base64 0.1.1, but your Gemfile requires base64 0.2.0. Since base64 is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports base64 as a default gem. (Gem::LoadError)
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:308:in `check_for_activated_spec!'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:25:in `block in setup'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/spec_set.rb:155:in `each'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/spec_set.rb:155:in `each'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:24:in `map'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:24:in `setup'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler.rb:161:in `setup'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/setup.rb:20:in `block in <top (required)>'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/ui/shell.rb:136:in `with_level'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/ui/shell.rb:88:in `silence'
App 388205 output:     /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/setup.rb:20:in `<top (required)>'
App 388205 output:     <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
App 388205 output:     <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
App 388205 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:382:in `activate_gem'
App 388205 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 388205 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:546:in `running_bundler'
App 388205 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 388205 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:91:in `preload_app'
App 388205 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 388205 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:399:in `run_block_and_record_step_progress'
App 388205 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 388205 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 388205 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2024-02-20 14:46:26.3523 387614/Tf age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/lib-jobs/current: The application encountered the following error: You have already activated base64 0.1.1, but your Gemfile requires base64 0.2.0. Since base64 is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports base64 as a default gem. (Gem::LoadError)
  Error ID: aaa2714b
  Error details saved to: /tmp/passenger-error-GMBHsz.html

[ E 2024-02-20 14:46:26.3632 387614/T8 age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is aaa2714b. Please see earlier logs for details about the error.
```

**Comment by maxkadel** [comment]
Run and deployed on both staging and production
